apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
        - name: greeting
          image: albihasani94/greeting
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: greeting
spec:
  selector:
    app: greeting
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer